(function(g){var window=this;var T4=function(a,b,c){var d=b.va();g.K(a.element,"ytp-suggestion-set",!!d.videoId);var e=b.getPlaylistId();c=b.zc(c?c:"mqdefault.jpg");var f=b instanceof g.dB&&b.lengthSeconds?g.KL(b.lengthSeconds):null,k=!!e;e=k&&"RD"===(new g.uD(e.substr(0,2),e.substr(2))).type;var l=b instanceof g.dB?b.ua:null;d={title:b.title,author:b.author,author_and_views:d.shortViewCount?b.author+" \u2022 "+d.shortViewCount:b.author,aria_label:b.yk||g.tM("Watch $TITLE",{TITLE:b.title}),duration:f,url:b.mi(),is_live:l,is_list:k,
is_mix:e,background:c?"background-image: url("+c+")":""};b instanceof g.vD&&(d.playlist_length=b.getLength());a.update(d)},U4=function(a){g.Q.call(this,{D:"div",
Y:["ytp-upnext","ytp-player-content"],O:{"aria-label":"{{aria_label}}"},K:[{D:"div",I:"ytp-cued-thumbnail-overlay-image",O:{style:"{{background}}"}},{D:"span",I:"ytp-upnext-top",K:[{D:"span",I:"ytp-upnext-header",W:"Up Next"},{D:"span",I:"ytp-upnext-title",W:"{{title}}"},{D:"span",I:"ytp-upnext-author",W:"{{author}}"}]},{D:"a",I:"ytp-upnext-autoplay-icon",O:{role:"button",href:"{{url}}","aria-label":"Play next video"},K:[{D:"svg",O:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},K:[{D:"circle",
I:"ytp-svg-autoplay-circle",O:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{D:"circle",I:"ytp-svg-autoplay-ring",O:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{D:"path",I:"ytp-svg-fill",O:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{D:"span",I:"ytp-upnext-bottom",K:[{D:"span",I:"ytp-upnext-cancel"},{D:"span",I:"ytp-upnext-paused",W:"Autoplay is paused"}]}]});
this.B=null;var b=this.o["ytp-upnext-cancel"];this.B=new g.Q({D:"button",Y:["ytp-upnext-cancel-button","ytp-button"],O:{tabindex:"0","aria-label":"Cancel autoplay"},W:"Cancel"});g.C(this,this.B);this.B.ia("click",this.wK,this);this.B.ba(b);this.u=a;this.J=this.o["ytp-svg-autoplay-ring"];this.F=this.C=this.w=this.A=null;this.G=new g.H(this.Bn,5E3,this);g.C(this,this.G);this.H=0;g.hL(this.u,this.element,this,18788);this.L(this.o["ytp-upnext-autoplay-icon"],"click",this.bM);this.dA();this.L(a,"autonavvisibility",
this.dA);this.L(a,"mdxnowautoplaying",this.vL);this.L(a,"mdxautoplaycanceled",this.wL);this.L(a,"mdxautoplayupnext",this.DC);3==this.u.getPresentingPlayerType()&&(a=(a=g.OK(g.HK(this.u)))?a.hF():null)&&this.DC(a);g.K(this.element,"ytp-upnext-mobile",this.u.N().o)},V4=function(a,b){if(!a.w){g.Uo("a11y-announce","Up Next "+a.A.title);
a.H=(0,g.N)();a.w=new g.H((0,g.x)(a.Dq,a,b),25);a.Dq(b);var c=b||g.S(a.u.N().experiments,"autoplay_time")||1E4;a.u.ma("onAutonavCoundownStarted",c)}g.Ln(a.element,"ytp-upnext-autoplay-paused")},X4=function(a){W4(a);
a.H=(0,g.N)();a.Dq();g.I(a.element,"ytp-upnext-autoplay-paused")},W4=function(a){a.w&&(a.w.dispose(),a.w=null)},Y4=function(a,b){g.Q.call(this,{D:"div",
Y:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.created=!1;this.player=a},vua=function(a){Y4.call(this,a,"subscribecard-endscreen");
var b=a.getVideoData();this.u=new g.Q({D:"div",I:"ytp-subscribe-card",K:[{D:"img",I:"ytp-author-image",O:{src:b.Jd}},{D:"div",I:"ytp-subscribe-card-right",K:[{D:"div",I:"ytp-author-name",W:b.author},{D:"div",I:"html5-subscribe-button-container"}]}]});g.C(this,this.u);this.u.ba(this.element);this.subscribeButton=new g.JP("Subscribe",null,"Unsubscribe",null,!0,!1,b.Kg,b.subscribed,"trailer-endscreen",null,null,a);g.C(this,this.subscribeButton);this.subscribeButton.ba(this.u.o["html5-subscribe-button-container"]);
this.hide()},Z4=function(a){var b=a.N(),c=g.ax||g.yh?{style:"will-change: opacity"}:void 0,d=b.u,e=["ytp-videowall-still"];
b.o&&e.push("ytp-videowall-show-text");g.Q.call(this,{D:"a",Y:e,O:{href:"{{url}}",target:d?b.A:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},K:[{D:"div",I:"ytp-videowall-still-image",O:{style:"{{background}}"}},{D:"span",I:"ytp-videowall-still-info",K:[{D:"span",I:"ytp-videowall-still-info-bg",K:[{D:"span",I:"ytp-videowall-still-info-content",O:c,K:[{D:"span",I:"ytp-videowall-still-info-title",W:"{{title}}"},{D:"span",I:"ytp-videowall-still-info-author",
W:"{{author_and_views}}"},{D:"span",I:"ytp-videowall-still-info-live",W:"Live"},{D:"span",I:"ytp-videowall-still-info-duration",W:"{{duration}}"}]}]}]},{D:"span",Y:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],K:[{D:"span",I:"ytp-videowall-still-listlabel-icon"},"Playlist",{D:"span",I:"ytp-videowall-still-listlabel-length",K:[" (",{D:"span",W:"{{playlist_length}}"},")"]}]},{D:"span",Y:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],K:[{D:"span",I:"ytp-videowall-still-listlabel-mix-icon"},
"Mix",{D:"span",I:"ytp-videowall-still-listlabel-length",W:" (50+)"}]}]});this.suggestion=null;this.u=d;this.api=a;this.w=new g.O(this);g.C(this,this.w);this.ia("click",this.onClick);this.ia("keypress",this.B);this.w.L(a,"videodatachange",this.A);g.iL(a,this.element,this);this.A()},$4=function(a){Y4.call(this,a,"videowall-endscreen");
var b=this;this.U=a;this.A=0;this.stills=[];this.B=this.videoData=this.suggestions=null;this.C=this.H=!1;this.G=null;this.w=new g.bQ(this);g.C(this,this.w);this.F=new g.H(function(){g.I(b.element,"ytp-show-tiles")},0);
g.C(this,this.F);var c=new g.Q({D:"button",Y:["ytp-button","ytp-endscreen-previous"],O:{"aria-label":"Previous"},K:[g.SL()]});g.C(this,c);c.ba(this.element);c.ia("click",this.tH,this);this.table=new g.Bt({D:"div",I:"ytp-endscreen-content"});g.C(this,this.table);this.table.ba(this.element);c=new g.Q({D:"button",Y:["ytp-button","ytp-endscreen-next"],O:{"aria-label":"Next"},K:[g.TL()]});g.C(this,c);c.ba(this.element);c.ia("click",this.sH,this);this.u=new U4(a);g.C(this,this.u);g.fL(this.player,this.u.element,
4);this.hide()},a5=function(a){return g.gL(a.player)&&a.Sv()&&!a.B},wua=function(a,b){return(0,g.Ec)(b.suggestions,function(c){c=g.VN(a.U.N(),c);
g.C(a,c);return c})},b5=function(a){var b=a.Os();
b!==a.H&&(a.H=b,a.player.P("autonavvisibility"))},c5=function(a){g.sL.call(this,a);
this.endScreen=null;this.listeners=new g.O(this);g.C(this,this.listeners);this.o=a.N();xua(a)?this.endScreen=new $4(this.player):this.o.Ja?this.endScreen=new vua(this.player):this.endScreen=new Y4(this.player);g.C(this,this.endScreen);g.fL(this.player,this.endScreen.element,4);this.LB();this.listeners.L(a,"videodatachange",this.LB,this);this.listeners.L(a,g.tD("endscreen"),this.pH,this);this.listeners.L(a,"crx_endscreen",this.qH,this)},xua=function(a){a=a.N();
return a.Ha&&!a.Ja};
g.r(U4,g.Q);g.h=U4.prototype;g.h.Bn=function(){this.C&&(this.G.stop(),this.Va(this.F),this.F=null,this.C.close(),this.C=null)};
g.h.dA=function(){g.Ft(this,g.IK(this.u));g.lL(this.u,this.element,g.IK(this.u))};
g.h.SL=function(){window.focus();this.Bn()};
g.h.hide=function(){g.Q.prototype.hide.call(this)};
g.h.Dq=function(a){a=a||g.S(this.u.N().experiments,"autoplay_time")||1E4;var b=Math.min((0,g.N)()-this.H,a);a=Math.min(b/a,1);this.J.setAttribute("stroke-dashoffset",-211*(a+1));1<=a&&3!=this.u.getPresentingPlayerType()?this.select(!0):this.w&&this.w.start()};
g.h.select=function(a){a=void 0===a?!1:a;if(g.R(this.u.N().experiments,"autonav_notifications")&&a&&window.Notification&&document.hasFocus){var b=Notification.permission;"default"==b?Notification.requestPermission():"granted"!=b||document.hasFocus()||(b=this.A.va(),this.Bn(),this.C=new Notification("Up Next",{body:b.title,icon:b.zc()}),this.F=this.L(this.C,"click",this.SL),this.G.start())}W4(this);this.u.nextVideo(!1,a)};
g.h.bM=function(a){!g.ze(this.B.element,g.Kp(a))&&g.zM(a,this.u)&&this.select()};
g.h.wK=function(){g.KK(this.u,!0)};
g.h.vL=function(a){this.u.getPresentingPlayerType();this.show();V4(this,a)};
g.h.DC=function(a){this.u.getPresentingPlayerType();this.A&&this.A.va().videoId==a.va().videoId||(this.A=a,T4(this,a,"hqdefault.jpg"))};
g.h.wL=function(){this.u.getPresentingPlayerType();W4(this);this.hide()};
g.h.X=function(){W4(this);this.Bn();g.Q.prototype.X.call(this)};g.r(Y4,g.Q);g.h=Y4.prototype;g.h.create=function(){this.created=!0};
g.h.destroy=function(){this.created=!1};
g.h.Sv=function(){return!1};
g.h.Os=function(){return!1};
g.h.Xx=function(){return!1};g.r(vua,Y4);g.r(Z4,g.Q);Z4.prototype.select=function(){var a=this.suggestion.va().videoId,b=this.suggestion.getPlaylistId();(g.oT(this.api.app,a,this.suggestion.Lb,b,void 0,void 0)||this.api.fa("web_player_endscreen_double_log_fix_killswitch"))&&g.kL(this.api,this.element)};
Z4.prototype.onClick=function(a){g.zM(a,this.api,this.u,this.suggestion.Lb||void 0)&&this.select()};
Z4.prototype.B=function(a){switch(a.keyCode){case 13:case 32:g.Pp(a)||(this.select(),g.Op(a))}};
Z4.prototype.A=function(){var a=this.api.getVideoData(),b=this.api.N();this.u=a.Ac?!1:b.u};g.r($4,Y4);g.h=$4.prototype;g.h.create=function(){Y4.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.suggestions=wua(this,a),this.videoData=a);this.Cg();this.w.L(this.player,"appresize",this.Cg);this.w.L(this.player,"onVideoAreaChange",this.Cg);this.w.L(this.player,"videodatachange",this.uH);this.w.L(this.player,"autonavchange",this.Ps);this.w.L(this.player,"autonavcancel",this.rH);a=this.videoData.autonavState;a!==this.G&&this.Ps(a);this.w.L(this.element,"transitionend",this.tN)};
g.h.destroy=function(){g.Lr(this.w);g.Ke(this.stills);this.stills=[];this.suggestions=null;Y4.prototype.destroy.call(this);g.Ln(this.element,"ytp-show-tiles");this.F.stop();this.G=this.videoData.autonavState};
g.h.Sv=function(){return 1!==this.videoData.autonavState};
g.h.show=function(){Y4.prototype.show.call(this);g.Ln(this.element,"ytp-show-tiles");this.player.N().o?g.Bn(this.F):this.F.start();(this.C||this.B&&this.B!==this.videoData.clientPlaybackNonce)&&g.KK(this.player,!1);a5(this)?(b5(this),2===this.videoData.autonavState?g.R(this.player.N().experiments,"fast_autonav_in_background")&&3===this.player.getVisibilityState()?this.u.select(!0):V4(this.u):3===this.videoData.autonavState&&X4(this.u)):(g.KK(this.player,!0),b5(this))};
g.h.hide=function(){Y4.prototype.hide.call(this);X4(this.u);b5(this)};
g.h.tN=function(a){g.Kp(a)===this.element&&this.Cg()};
g.h.Cg=function(){if(this.suggestions&&this.suggestions.length){g.I(this.element,"ytp-endscreen-paginate");var a=g.XK(this.U,!0,this.U.isFullscreen()),b=g.gC(this.U);b&&(b=b.qc()?48:32,a.width-=2*b);var c=a.width/a.height,d=96/54,e=b=2,f=Math.max(a.width/96,2),k=Math.max(a.height/54,2),l=this.suggestions.length,m=Math.pow(2,2);var n=l*m+(Math.pow(2,2)-m);n+=Math.pow(2,2)-m;for(n-=m;0<n&&(b<f||e<k);){var p=b/2,t=e/2,u=b<=f-2&&n>=t*m,z=e<=k-2&&n>=p*m;if((p+1)/t*d/c>c/(p/(t+1)*d)&&z)n-=p*m,e+=2;else if(u)n-=
t*m,b+=2;else if(z)n-=p*m,e+=2;else break}d=!1;n>=3*m&&6>=l*m-n&&(4<=e||4<=b)&&(d=!0);m=96*b;n=54*e;c=m/n<c?a.height/n:a.width/m;c=Math.min(c,2);m*=c;n*=c;m*=g.Od(a.width/m||1,1,1.21);n*=g.Od(a.height/n||1,1,1.21);m=Math.floor(Math.min(a.width,m));n=Math.floor(Math.min(a.height,n));a=this.table.element;g.Nh(a,m,n);g.vh(a,{marginLeft:m/-2+"px",marginTop:n/-2+"px"});c=this.u;f=this.suggestions[0];c.A=f;T4(c,f,"hqdefault.jpg");g.K(this.element,"ytp-endscreen-takeover",a5(this));b5(this);m+=4;n+=4;for(f=
c=0;f<b;f++)for(k=0;k<e;k++)if(p=c,t=0,d&&f>=b-2&&k>=e-2?t=1:0===k%2&&0===f%2&&(2>k&&2>f?0===k&&0===f&&(t=2):t=2),p=g.Pd(p+this.A,l),0!==t){u=this.stills[c];u||(u=new Z4(this.player),this.stills[c]=u,a.appendChild(u.element));z=Math.floor(n*k/e);var B=Math.floor(m*f/b),D=Math.floor(n*(k+t)/e)-z-4,E=Math.floor(m*(f+t)/b)-B-4;g.Dh(u.element,B,z);g.Nh(u.element,E,D);g.vh(u.element,"transitionDelay",(k+f)/20+"s");g.K(u.element,"ytp-videowall-still-mini",1===t);g.K(u.element,"ytp-videowall-still-large",
2<t);t=u;p=this.suggestions[p];t.suggestion!==p&&(t.suggestion=p,u=t.api.N(),z=g.Jn(t.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",T4(t,p,z),g.Iy(u)&&(u=p.mi(),u=g.Ad(u,g.aD({},"emb_rel_end")),t.ka("url",u)),(p=(p=p.Lb)&&p.itct)&&g.jL(t.api,t.element,p));c++}g.K(this.element,"ytp-endscreen-paginate",c<l);for(b=this.stills.length-1;b>=c;b--)e=this.stills[b],g.ve(e.element),g.Je(e);this.stills.length=c}};
g.h.uH=function(){var a=this.player.getVideoData();this.videoData!==a&&(this.A=0,this.suggestions=wua(this,a),this.videoData=a,this.Cg())};
g.h.sH=function(){this.A+=this.stills.length;this.Cg()};
g.h.tH=function(){this.A-=this.stills.length;this.Cg()};
g.h.Xx=function(){return!!this.u.w};
g.h.Ps=function(a){1===a?(this.C=!1,this.B=this.videoData.clientPlaybackNonce,W4(this.u),this.Fa()&&this.Cg()):(this.C=!0,this.Fa()&&a5(this)&&(2===a?V4(this.u):3===a&&X4(this.u)))};
g.h.rH=function(a){if(a){for(a=0;a<this.stills.length;a++)g.lL(this.U,this.stills[a].element,!0);this.Ps(1)}else this.B=null,this.C=!1;this.Cg()};
g.h.Os=function(){return this.Fa()&&a5(this)};g.r(c5,g.sL);g.h=c5.prototype;g.h.yy=function(){var a=this.player.getVideoData(),b=!!(a&&a.suggestions&&a.suggestions.length);b=!xua(this.player)||b;var c=a.bj||g.Ry(a.Qa),d=g.IS(this.player.app);a=a.mutedAutoplay;return b&&!c&&!d&&!a};
g.h.wy=function(){return this.endScreen.Os()};
g.h.dG=function(){return this.wy()?this.endScreen.Xx():!1};
g.h.X=function(){g.vQ(this.player.app,"endscreen",void 0);g.sL.prototype.X.call(this)};
g.h.load=function(){g.sL.prototype.load.call(this);this.endScreen.show()};
g.h.unload=function(){g.sL.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.h.pH=function(a){this.yy()&&(this.endScreen.created||this.endScreen.create(),"load"===a.getId()&&this.load())};
g.h.qH=function(a){"load"===a.getId()&&this.loaded&&this.unload()};
g.h.LB=function(){g.vQ(this.player.app,"endscreen",void 0);var a=this.player.getVideoData();a=new g.qD(Math.max(1E3*(a.lengthSeconds-10),0),0x8000000000000,{id:"preload",namespace:"endscreen"});var b=new g.qD(0x8000000000000,0x8000000000000,{id:"load",priority:6,namespace:"endscreen"});g.bL(this.player,[a,b])};g.HL.endscreen=c5;})(_yt_player);
